// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Aurigo.Atom.Generator.Core.CodeGenTemplates.BasicTemplate
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MasterRunner_AutoGenTestsTemplate : MasterRunner_AutoGenTestsTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n\r\nusing AurigoTest.Toolkit;\r\nusing AurigoTest.Toolkit.Core;\r\nusing ");
            
            #line 9 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorMasterRunner_AutoGenTests.ModuleId));
            
            #line default
            #line hidden
            this.Write("_TestSuite.AutoGenTests;\r\nusing System;\r\nusing System.Collections.Generic;\r\n\r\nnam" +
                    "espace ");
            
            #line 13 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorMasterRunner_AutoGenTests.AutoGeneratedProjectNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public class MasterRunner_AutoGenTests : ITestSuiteBase\r\n    {\r\n        " +
                    "public string SuiteName { get { return \"");
            
            #line 17 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorMasterRunner_AutoGenTests.SuiteName));
            
            #line default
            #line hidden
            this.Write(@"""; } }

        public void RunTest(List<string> testMethodsToRun = null)
        {
            TC tc = new TC();

            List<Action<string, string>> testMethodChain = new List<Action<string, string>>();

            foreach (var methodName in testMethodsToRun)
            {
                var methodRef = GetMethodReference(methodName, ref tc);
                if (methodRef != null)
                    testMethodChain.Add(methodRef);
            }

            var testRunDescription = ""ALL"";

            if (testMethodsToRun == null)
                testMethodChain = GetAllMethodReference(ref tc);
            else
                testRunDescription = string.Join("","", testMethodsToRun);

			try
			{
	            TestRunner.RunWithDesc(""");
            
            #line 41 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorMasterRunner_AutoGenTests.SuiteName));
            
            #line default
            #line hidden
            this.Write(@""", ""Running: "" + testRunDescription, testMethodChain, tc);
			}
			catch(Exception e)
			{
			}
			finally
            {
                Helpers.Report.Close(); //THIS HAS TO BE DONE so report is created

                if (System.IO.File.Exists(Helpers.ReportFileFullPath))
                    System.Diagnostics.Process.Start(Helpers.ReportFileFullPath);
            } 
        }

        protected Action<string, string> GetMethodReference(string methodName, ref TC tc)
        {
            switch (methodName)
            {
			");
            
            #line 59 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
 foreach( var item in GeneratorMasterRunner_AutoGenTests.ComputedList_For_ScenarioMethod) {  
            
            #line default
            #line hidden
            this.Write("\t\t\t\tcase \"");
            
            #line 60 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\": return tc.");
            
            #line 60 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t");
            
            #line 61 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
  }  
            
            #line default
            #line hidden
            this.Write("            }\r\n            return null;\r\n        }\r\n\r\n        protected List<Acti" +
                    "on<string, string>> GetAllMethodReference(ref TC tc)\r\n        {\r\n            Lis" +
                    "t<Action<string, string>> testMethodChain = new List<Action<string, string>>();\r" +
                    "\n\r\n\t\t\t");
            
            #line 70 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
 foreach( var item in GeneratorMasterRunner_AutoGenTests.ComputedList_For_ScenarioMethod) {  
            
            #line default
            #line hidden
            this.Write("\t\t\t\ttestMethodChain.Add(tc.");
            
            #line 71 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t");
            
            #line 72 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"
  }  
            
            #line default
            #line hidden
            this.Write("\r\n            return testMethodChain;\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\TFS_REPO\Hackathon2018_ATOM\Aurigo.Atom.Generator.Core\CodeGenTemplates\BasicTemplate\MasterRunner_AutoGenTestsTemplate.tt"

private global::Aurigo.Atom.Generator.Core.CodeGenObjects.BasicTemplate.GeneratorMasterRunner_AutoGenTests _GeneratorMasterRunner_AutoGenTestsField;

/// <summary>
/// Access the GeneratorMasterRunner_AutoGenTests parameter of the template.
/// </summary>
private global::Aurigo.Atom.Generator.Core.CodeGenObjects.BasicTemplate.GeneratorMasterRunner_AutoGenTests GeneratorMasterRunner_AutoGenTests
{
    get
    {
        return this._GeneratorMasterRunner_AutoGenTestsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool GeneratorMasterRunner_AutoGenTestsValueAcquired = false;
if (this.Session.ContainsKey("GeneratorMasterRunner_AutoGenTests"))
{
    this._GeneratorMasterRunner_AutoGenTestsField = ((global::Aurigo.Atom.Generator.Core.CodeGenObjects.BasicTemplate.GeneratorMasterRunner_AutoGenTests)(this.Session["GeneratorMasterRunner_AutoGenTests"]));
    GeneratorMasterRunner_AutoGenTestsValueAcquired = true;
}
if ((GeneratorMasterRunner_AutoGenTestsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GeneratorMasterRunner_AutoGenTests");
    if ((data != null))
    {
        this._GeneratorMasterRunner_AutoGenTestsField = ((global::Aurigo.Atom.Generator.Core.CodeGenObjects.BasicTemplate.GeneratorMasterRunner_AutoGenTests)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class MasterRunner_AutoGenTestsTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
