using Aurigo.Atom.Generator.Core.CodeGenObjects.BasicTemplate;
using Aurigo.Atom.Generator.Core.CodeGenTemplates.BasicTemplate;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Aurigo.Atom.Generator.Core.CodeSolutionBuilder
{
    public class MasterRunnerUserCSharpFileGenerator : AbstractFileGeneratorBase
    {
        //public GeneratorMasterRunner_AutoGenTests TemplateDataObject { get; private set; }
        public string AutoGeneratedProjectNamespace { get { return ModuleId + "_TestSuite"; } }
        public string ModuleId { get; set; }
        public MasterRunnerUserCSharpFileGenerator(string moduleId, string suiteName)
        {
            this.ModuleId = moduleId;

            //this.TemplateDataObject = new GeneratorMasterRunner_AutoGenTests()
            //{
            //    ModuleName = moduleName,
            //    SuiteName = suiteName,
            //};
        }

        //public void AddScenarioMethodName(string scenarioMethodName)
        //{
        //    this.TemplateDataObject.ComputedList_For_ScenarioMethod.Add(scenarioMethodName);
        //}

        protected override string FileName { get { return "MasterRunner_UserTests.cs"; } }

        protected override string GetFileContent()
        {
            return @"
using AurigoTest.Toolkit;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace "+ AutoGeneratedProjectNamespace + @"
{
    public class MasterRunner_UserTests : ITestSuiteBase
    {
        public string SuiteName { get { return """ + this.ModuleId + @"_TestSuite_UserTests""; } }

        public void RunTest(List<string> testMethodsToRun = null)
        {
            throw new NotImplementedException();
        }
    }
}";
        }
    }
}
