namespace Aurigo.Atom.Common.DTO
{
    /// <summary>
    ///
    /// </summary>
    public class TestModuleConfig
    {
        public string AutoGeneratedProjectNamespace { get { return ModuleId + "_TestSuite"; } }

        /// <summary>
        /// Gets or sets the module identifier.
        /// </summary>
        /// <value>
        /// The module identifier.
        /// </value>
        public string ModuleId { get; set; }

        /// <summary>
        /// Gets or sets the name of the module.
        /// </summary>
        /// <value>
        /// The name of the module.
        /// </value>
        public string ModuleName { get; set; }

        /// <summary>
        /// Gets or sets the name of the table.
        /// </summary>
        /// <value>
        /// The name of the table.
        /// </value>
        public string TableName { get; set; }

        /// <summary>
        /// Gets or sets the name of the primary key column.
        /// </summary>
        /// <value>
        /// The name of the primary key column.
        /// </value>
        public string PrimaryKeyColumnName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [verify in edit mode].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [verify in edit mode]; otherwise, <c>false</c>.
        /// </value>
        public bool VerifyInEditMode { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [verify in view mode].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [verify in view mode]; otherwise, <c>false</c>.
        /// </value>
        public bool VerifyInViewMode { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [include negative test case].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [include negative test case]; otherwise, <c>false</c>.
        /// </value>
        public bool IncludeNegativeTestCase { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether [include security test case].
        /// </summary>
        /// <value>
        ///   <c>true</c> if [include security test case]; otherwise, <c>false</c>.
        /// </value>
        public bool IncludeSecurityTestCase { get; set; }

        /// <summary>
        /// Gets or sets the template path.
        /// </summary>
        /// <value>
        /// The template path.
        /// </value>
        public string TemplatePath { get; set; }

        /// <summary>
        /// Gets or sets the name of the automation unique identifier field.
        /// </summary>
        /// <value>
        /// The name of the automation unique identifier field.
        /// </value>
        public string AutomationGuidFieldName { get; set; }

        /// <summary>
        /// Get or Sets the Assembly name
        /// </summary>
        public string AssemblyName { get; set; }

        public TestBuildCredentials Credentials { get; set; }
        public SolutionGenerationConfig SolutionConfig { get; set; }
    }

    public class TestBuildCredentials
    {
        public string URL { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConnectionString { get; set; }
    }
}